name: SMoE_X2
model_type: SRModel
scale: 2
num_gpu: auto
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    task: SR
    name: AID
    type: PairedImageDataset
    dataroot_gt:
      - /AID/train/HR
    dataroot_lq:
      - /AID/train/LR/x2
    filename_tmpl: '{}_x2'
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: True
    use_rot: True

    # data loader
    use_shuffle: True
    num_worker_per_gpu: 18
    batch_size_per_gpu: 32
    dataset_enlarge_ratio: 50
    prefetch_mode: cuda
    pin_memory: True

  val:
    name: AID_val
    type: PairedImageDataset
    dataroot_gt: /AID/val/HR
    dataroot_lq: /AID/val/LR/x2
    filename_tmpl: '{}_x2'
    io_backend:
      type: disk

# network structures
network_g:
  type: HFDMMamba
  scale: 2
  in_chans: 3
  num_experts: 3
  img_range: 1.
  num_layers: 8
  embedding_dim: 48
  use_shuffle: True
  lr_space: exp
  topk: 1
  recursive: 1
  d_state: 10

# path
path:
  pretrain_network_g: /home/waas/MambaIR-main/experiments/SS2D_SeemoRe_B_X2/models/net_g_255000.pth
  strict_load_g: False
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-3
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    # milestones: [125000, 200000, 225000, 237500]
    gamma: 0.5

  total_iter: 500000
  # total_iter: 250000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 2500
  save_img: False

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: True

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 2500
  use_tb_logger: True
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
